/**
 * Fun-text commands part 2 — anime/action reactions + fantasy "power" readings
 * (KHANTHEHACKER-style FUN TEXT section). Family-friendly, entertainment only.
 * Anyone can use these. Usage: .hug .ninja .dragonfire .coin etc.
 */
const RESPONSES = {
    // ---- anime / action reactions ----
    angry: "😠 *Angry!* Gussa naak par hai? Gehri saans lo, chai piyo, sab theek ho jayega! 😤",
    baka: "🤪 *Baka!* Oye baka! Tum to anime ke hero ho — thora pagal, bohat pyaara! ✨",
    bleh: "😝 *Bleh!* Blehhh! Zabaan nikaal di! Bachpan wali shararat yaad aa gayi! 👅",
    blowkiss: "😘💨 *Blow Kiss!* Ek hawaai pappi aap ki taraf ur rahi hai! Pakar liya? 💋",
    cake: "🍰 *Cake!* Cake kaato, khushiyan baanto! Chocolate wala sab se best! 🎂",
    carry: "🏋️ *Carry!* Aap ne dosti ko kandhon par utha liya! Itne strong! 💪",
    celebrate: "🎉 *Celebrate!* Party time! Dhol bajao, nacho gao! 🥳",
    clap: "👏 *Clap!* Taaliyan baj rahi hain! Kya performance di hai! Encore! 👏👏",
    coin: "🪙 *Coin!* Sikka uchala... *HEADS!* Aaj qismat aap ke saath hai! 🍀",
    confused: "😕 *Confused!* Dimagh ghum gaya? Ruko, gehri saans lo, phir decide karo! 🌀",
    cool: "😎 *Cool!* Itne cool ke barf bhi sharma jaye! Style on point! ❄️",
    cosplay: "🎭 *Cosplay!* Aap ka cosplay to bilkul original lagta hai! Character unlocked! 🦸",
    emoji: "😀 *Emoji!* 😍🔥✨ Aap khud ek walking emoji ho! Mazedaar! 🎉",
    facepalm: "🤦 *Facepalm!* Uff... ye dekh kar haath seedha chehre par aa gaya! 😅",
    feed: "🍽️ *Feed!* Khaana khilao, pyaar barhao! Mehmaan nawazi zindabad! 😋",
    handshake: "🤝 *Handshake!* Deal pakki! Dosti ka waada, pakka waada! 💪",
    headbang: "🤘 *Headbang!* Music tez karo, sar hilao! Rock on! 🎸",
    horoscope: "🔮 *Horoscope!* Aaj ka din: khushiyan, chai aur achi khabar! Sitare aap ke saath hain! ⭐",
    img: "🖼️ *Img!* Tasveer hazar lafzon se zyada kehti hai! Smile! 📸",
    kabedon: "😳 *Kabedon!* Deewar par haath... dil ki dhadkan tez! Full anime moment! 💓",
    laugh: "😂 *Laugh!* Hahaha! Hansi to phoot pari! Dil khush kar diya! 🤣",
    lurk: "👀 *Lurk!* Chupke dekh rahe ho? Pakre gaye! Bahar aao, baat karo! 😏",
    no: "🚫 *No!* Nahi matlab NAHI! Final decision, no appeal! 😤",
    nod: "🙂 *Nod!* Sar hila diya — matlab samajh gaye! Smart ho! 👍",
    nope: "🙅 *Nope!* Nope nope nope! Ye to nahi hoga! 😜",
    nosebleed: "🩸 *Nosebleed!* Itna cute dekha ke naak se khoon aa gaya! Anime style! 😳",
    nuzzle: "🥰 *Nuzzle!* Pyaar bhari chhuan! Dil garam ho gaya! 💕",
    nya: "🐱 *Nya!* Nya nya! Billi wali cuteness overload! Meow! 🐾",
    peck: "😗 *Peck!* Gaal par halki si pappi! Meethi meethi! 💋",
    pout: "😗 *Pout!* Hont phula liye? Itne cute lag rahe ho! 🥺",
    punch: "👊 *Punch!* DHISHUM! Boriyat ko ek zor ka mukka para! 💥",
    rizz: "😏 *Rizz!* Rizz level: LEGENDARY! Baaton se hi dil jeet liya! ✨",
    run: "🏃 *Run!* Bhaago! Kaam peeche par gaya hai! Fast fast! 💨",
    sad: "😢 *Sad!* Udaas mat ho! Ye lo virtual jhappi! Sab theek ho jayega! 🤗",
    scared: "😱 *Scared!* Dar lag raha hai? Dar ke aage jeet hai! Himmat karo! 💪",
    shake: "🤝 *Shake!* Haath milao! Dosti pakki, dushmani khatam! 😄",
    shocked: "😲 *Shocked!* Kya?! Ye sun kar to hosh ur gaye! 😱",
    shoot: "🔫 *Shoot!* Pew pew! Nishana bilkul sahi! Sharpshooter! 🎯",
    shrug: "🤷 *Shrug!* Pata nahi! Kandhe uchka diye! Jo hoga dekha jayega! 😅",
    shy: "🙈 *Shy!* Sharmate hue gaal laal! Kitne pyaare lag rahe ho! 🌸",
    sigh: "😮‍💨 *Sigh!* Gehri saans... tension bahar, sukoon andar! 🧘",
    sigma: "🐺 *Sigma!* Lone wolf mode ON! Apni duniya ke badshah! 👑",
    simp: "🥺 *Simp!* Itna pyaar? Dil to diya hi, ab dimagh bhi de diya! 😂",
    sip: "☕ *Sip!* Chai ki ek chuski... Ahh! Duniya ke saare gham bhool gaye! 😌",
    sleep: "😴 *Sleep!* Neend aa rahi hai? Khwaabon mein milte hain! Good night! 🌙",
    spin: "🌀 *Spin!* Ghoom ghoom! Chakkar aa gaye? Maza to aya! 😵‍💫",
    stare: "👀 *Stare!* Itna ghoor rahe ho? Aankhein dukh jayengi! 😂",
    stop: "✋ *Stop!* Ruko! Bas karo! Ab aage nahi! 🛑",
    surprised: "😮 *Surprised!* Wah! Ye to surprise tha! Dil khush ho gaya! 🎁",
    tableflip: "┻━┻ *Table Flip!* Table ulta di! Gussa nikaal diya! Ab sukoon! 😤",
    taroun: "✨ *Taroun!* Aap chamak rahe ho! Sitare bhi jealous! 🌟",
    teehee: "😊 *Teehee!* Teehee! Shararti hansi! Kuch to gadbad hai! 😏",
    think: "🤔 *Think!* Soch mein par gaye? Dimagh ke ghore dauda rahe ho! 🧠",
    thumbsup: "👍 *Thumbs Up!* Shabash! Bilkul sahi! Approved! ✅",
    tickle: "🤭 *Tickle!* Gudgudi! Hahaha ruko ruko! Hansi nahi ruk rahi! 😂",
    tired: "😩 *Tired!* Thak gaye? Aaram karo, chai piyo! Kal phir larenge! ☕",
    vibe: "✌️ *Vibe!* Vibe check: 100% positive! Aap ke saath maza hai! 🎶",
    yawn: "🥱 *Yawn!* Ubaasi aa rahi hai? Neend ka time ho gaya! 😴",
    yay: "🎉 *Yay!* Yayyy! Jeet gaye! Khushi ke maare uchal paro! 🥳",
    yes: "✅ *Yes!* Haan matlab HAAN! Done deal! Pakki baat! 😄",

    // ---- fantasy "power" readings (pure entertainment) ----
    alchemist: "⚗️ *Alchemist!* Aap ke haathon mein sona banane ka hunar hai! Chai ko sukoon mein badal dete ho! ✨",
    alieninvasion: "👽 *Alien Invasion!* UFO nazar aya! Lagta hai aliens bhi aap ke fan hain! 🛸",
    astral: "🌌 *Astral!* Aap ki rooh sitaron mein safar kar rahi hai! Cosmic energy full! ✨",
    atlantis: "🌊 *Atlantis!* Doobi hui duniya ka raaz! Aap ke andar samandar jaisa gehra dil hai! 🐚",
    cd: "💿 *CD!* Purani yaadein, purane gaane! CD ghumao, nostalgia ON! 🎶",
    centaur: "🏹 *Centaur!* Aadha insaan, aadha ghora — taqat aur aqal ka perfect combo! ⚡",
    chumi: "😽 *Chumi!* Chumi chumi! Billi wali pyaari chhuan! Meow! 🐱",
    clock: "🕐 *Clock!* Tik tok tik tok! Waqt kisi ka intezar nahi karta! ⏰",
    conjurer: "🎩 *Conjurer!* Topi se kabootar nikaal diya! Jadoo ho gaya! 🐇",
    cyborg: "🤖 *Cyborg!* Aadha insaan, aadha machine! Future aap ke saath hai! ⚙️",
    diviner: "🔮 *Diviner!* Mustaqbil ki jhalak! Sitare kehte hain — khush khabri qareeb hai! ✨",
    dragonfire: "🐉 *Dragonfire!* Aap ke andar dragon wali aag hai! Jazba itna ke pahar pighal jayein! 🔥",
    earthquake: "🌍 *Earthquake Power!* Aap ki entry se zameen hil jati hai! Itna asar! (sirf mazaak mein 😄)",
    enchanter: "✨ *Enchanter!* Aap ki baton mein jadoo hai! Jo sune, deewana ho jaye! 💫",
    fairy: "🧚 *Fairy!* Pariyon wali duniya se! Jahan jao, khushiyan bikher do! 🌸",
    fing: "👆 *Fing!* Ek ungli uthai — faisla suna diya! Judge mode ON! ⚖️",
    gladiator: "⚔️ *Gladiator!* Maidan mein utar aaye! Himmat aur taqat ka namuna! 🛡️",
    griffin: "🦅 *Griffin!* Sher aur uqaab ka jod! Aap mein dono ki taqat hai! 🦁",
    guru: "🧘 *Guru!* Gyaan ka samandar! Aap ki ek baat zindagi badal de! 🙏",
    heart: "❤️ *Heart!* Dil bara rakho! Pyaar banto, pyaar pao! 💖",
    hurricane: "🌀 *Hurricane Energy!* Aap ke jazbe ka toofan! Rukna aap ki fitrat mein nahi! (fun mode 😄)",
    illusionist: "🎩 *Illusionist!* Nazar ka dhokha! Aap ne sab ko hairan kar diya! ✨",
    knight: "🛡️ *Knight!* Bahadur sipahi! Aap ki talwar sirf insaaf ke liye uthti hai! ⚔️",
    loading: "⏳ *Loading...* Sabar karo! 99% complete... bas thora aur! 😅",
    mayan: "🏛️ *Mayan!* Qadeem tehzeeb ka raaz! Aap mein purani hikmat chhupi hai! 📜",
    medium: "🔮 *Medium!* Roohon se rabta? Nahi nahi — bas mazedaar andazay! 😄",
    mermaid: "🧜‍♀️ *Mermaid!* Samandar ki shehzadi! Aap ki muskaan lehren jaisi! 🌊",
    monk: "🧘 *Monk!* Sukoon ka raasta! Aap ke paas andar ki taqat hai! 🕊️",
    moon: "🌙 *Moon!* Chaandni raat! Aap ka chehra chand se kam nahi! ✨",
    mystic: "🌟 *Mystic!* Raazdaar shakhsiyat! Aap mein gehri gehraayi hai! 🔮",
    necromancer: "💀 *Necromancer!* Purani yaadein zinda kar di! (sirf yaadein, promise 😄)",
    nikal: "🚶 *Nikal!* Nikal paray! Shararaton ke maidan mein! Maza karo! 😎",
    ninja: "🥷 *Ninja!* Chupke chupke! Aap to ninja ki tarah har kaam perfect karte ho! ⚡",
    olympus: "🏛️ *Olympus!* Dewtaon ka ghar! Aap ki shaksiyat bhi shahi hai! 👑",
    oracle: "🔮 *Oracle!* Peshgoi: aaj aap ko achi khabar milegi! Yaqeen rakho! ✨",
    pegasus: "🦄 *Pegasus!* Paron wala ghora! Aap ke khwaab unche urte hain! ☁️",
    pharaoh: "👑 *Pharaoh!* Misr ke badshah! Aap ki shaan nirali! 🏺",
    phoenix: "🔥 *Phoenix!* Raakh se dobara janam! Aap har mushkil se ubharte ho! 🦅",
    pirate: "🏴‍☠️ *Pirate!* Samandar ke lutere! Asli khazana to dosti hai! 🗺️",
    prophet: "📜 *Prophet Wisdom!* Hikmat bhari baat: sabar ka phal meetha hota hai! 🌟",
    rocket: "🚀 *Rocket!* 3... 2... 1... URAN! Aap ki kamyabi aasmaan chhuegi! 🌠",
    sage: "🧙 *Sage!* Dana shakhs! Aap ki salah sonay se keemti hai! 💎",
    samurai: "⚔️ *Samurai!* Izzat aur wafadari ka paikar! Katana taiyaar! 🗡️",
    seer: "👁️ *Seer!* Door ki nazar! Aap ko pehle hi sab pata chal jata hai! 🔮",
    shaman: "🌿 *Shaman!* Qudrat se jura rishta! Aap mein roohani taqat hai! ✨",
    sorcerer: "🪄 *Sorcerer!* Jadoo ki chhadi ghumai! Ab sab kuch mumkin! ✨",
    spartan: "🛡️ *Spartan!* 300 wali himmat! Aap kabhi peeche nahi hat te! ⚔️",
    spinner: "🌀 *Spinner!* Chakkar ghumao! Fidget wala sukoon! 😄",
    telepath: "🧠 *Telepath!* Dimagh parh liya! Soch rahe ho na — ye kaise pata chala? 😏",
    tornado: "🌪️ *Tornado Energy!* Aap ki raftaar ka toofan! Koi rok nahi sakta! (fun mode 😄)",
    tsunami: "🌊 *Tsunami Vibes!* Aap ke jazbat ki lehar! Pyaar ka samandar! (sirf masti 😄)",
    type: "⌨️ *Type!* Typing speed: 100 WPM! Ungliyan bijli ki tarah chalti hain! ⚡",
    valhalla: "⚔️ *Valhalla!* Bahaduron ka ghar! Aap ki jagah wahan pakki! 🍻",
    vampire: "🧛 *Vampire!* Raat ke shehzade! Bas khoon nahi, chai peete hain! ☕",
    viking: "🪓 *Viking!* Samandaron ke fateh! Aap ki himmat misali! ⛵",
    volcano: "🌋 *Volcano Power!* Andar lava jaisa jazba! Jab bolo to kamal! 🔥",
    werewolf: "🐺 *Werewolf!* Purnima ki raat... AWOOO! Chaand ke deewane! 🌕",
    witchspell: "🧙‍♀️ *Witch Spell!* Jadoo chal gaya! Ab sab kuch aap ke haq mein! ✨",
    wizardmagic: "🪄 *Wizard Magic!* Expecto... MAZA! Jadoo ho gaya! 🎇",
    wthr: "🌤️ *Weather!* Aaj ka mausam: khushgawar, halki hansi ke saath! 😊",
    yogi: "🧘 *Yogi!* Dhyaan lagao, sukoon pao! Aap ke andar shanti hai! 🕉️",
    zombie: "🧟 *Zombie!* Brainzzz... matlab BIRYANIZZZ! 🍛😂",
};

async function funText2Command(sock, chatId, msg, trigger) {
    const key = String(trigger || '').toLowerCase();
    const text = RESPONSES[key];
    if (!text) return;
    try {
        await sock.sendMessage(chatId, { text }, { quoted: msg });
    } catch (e) {
        console.error('FunText2 command error:', e.message);
    }
}

module.exports = funText2Command;
module.exports.TRIGGERS = Object.keys(RESPONSES);
