/**
 * Fun-text / desi masti commands (KHANTHEHACKER-style FUN TEXT section).
 * Each trigger sends a short playful family-friendly message. Usage: .ishqmeter, .dillagi, etc.
 * Anyone can use these.
 */
const RESPONSES = {
    ishqmeter: "💘 *Ishq Meter:* 98%! Aap ke dil ka meter full hai! Lagta hai kisi ne dil chura liya hai! 😄",
    andhaishq: "🙈 *Andha Ishq!* Dekha nahi, bas dil lag gaya! Yehi to asli ishq hai — bina dekhe wala! 😂",
    lafzmohabbat: "💬 *Lafz-e-Mohabbat!* Mohabbat lafzon mein nahi, ehsaas mein hoti hai. Phir bhi kehne mein kya harj! 💕",
    pehlinazar: "👀 *Pehli Nazar!* Pehli nazar wala pyaar aakhri tak yaad rehta hai! Dil sambhal ke! ✨",
    dillagi: "😜 *Dillagi!* Dil lagana asaan, nibhana mushkil! Dillagi mein kisi ka dil mat todo! 💔",
    khoobsurat: "🌹 *Khoobsurat!* Aap itne khoobsurat ho ke aaina bhi sharma jaye! MashaAllah! 😍",
    dhadkan: "💓 *Dhadkan!* Dhadkan tez ho rahi hai... lagta hai koi khaas yaad aa raha hai! 😏",
    pehlaakhat: "💌 *Pehla Khat!* Pehle khat ki mithaas hi alag hoti hai! Alfaaz dil se nikle hon to asar karte hain! 💝",
    ziddidil: "😤 *Ziddi Dil!* Ye dil to ziddi hai, jo chaha wahi manga! Zid mein hi maza hai! 🔥",
    yaadaata: "🌙 *Yaad Aata Hai!* Koi door hokar bhi dil ke qareeb hai — yaadein hi to zindagi hain! 💭",
    taubatauba: "😱 *Tauba Tauba!* Itna pyaar? Tauba tauba, dil sambhal ke rakho! 😂",
    pehlamuhabbat: "💖 *Pehli Mohabbat!* Pehli mohabbat kabhi bhooli nahi jati — dil ke kone mein hamesha rehti hai! 🥺",
    wafaimtihaan: "⚖️ *Wafa Imtihaan!* Wafa ka imtihaan mushkil hota hai, lekin jo pass ho jaye wo dil jeet le! 💪",
    donokikahani: "📖 *Dono Ki Kahani!* Ek tha raja, ek thi rani — dono ne likhi apni kahani! Aap ki kab shuru hogi? 😄",
    gulabbhejo: "🌹 *Gulaab Bhejo!* Ek gulaab bhejo, dil ka haal keh do! Gulaab ki baat seedhi dil tak jati hai! 💌",
    aankhein: "👁️ *Aankhein!* Aankhein sab keh deti hain — jo zubaan nahi kehti! Aap ki kya keh rahi hain? 😏",
    shayarban: "🖋️ *Shayar Ban!* Wah wah! Aap to shayar ban gaye! Alfaaz mein jadoo hai! 👏",
    dushmandost: "🤝 *Dushman Dost!* Kal ka dushman aaj ka dost! Waqt badalte der nahi lagti! 😄",
    tangkarna: "😝 *Tang Karna!* Dost ko tang karna dosti ka pehla usool hai! Lekin hadd mein reh kar! 😂",
    smilechurao: "😁 *Smile Churao!* Kisi ki smile churana sab se meetha jurm hai! Muskurate raho! ✨",
    jaan: "❤️ *Jaan!* Aap to kisi ki jaan ho! Jaan se pyaari cheez kya hogi! 🥰",
    qismatwala: "🍀 *Qismat Wala!* Achay dost, acha dil — aap bohat qismat wale ho! Qadar karo! 😄",
    jhoothpyaar: "🤥 *Jhootha Pyaar!* Ye dialogue to har teesra banda bolta hai! Asli wale pehchano! 😂",
    siyaanibaat: "🧠 *Siyaani Baat!* Mohabbat mein aqal nahi, dil chalta hai! Bara siyaana keh gaya! 💡",
    mohabbatqarz: "💸 *Mohabbat Qarz!* Mohabbat qarz nahi jo wapas mangi jaye! Dil se do, hisaab mat rakho! 💝",
    nazarutarao: "🧿 *Nazar Utarao!* Itni tareef ke baad nazar utarna banta hai! Buri nazar se bacho! 🤲",
    romanticbakwaas: "🌹 *Romantic Bakwaas!* Bas karo, zyada romantic mat bano! Thora control! 😂",
    aashiqanaaward: "🏆 *Aashiqana Award!* Best Aashiq ka award jata hai... AAP KO! Taaliyan! 👏😄",
    mohabbatteri: "💕 *Mohabbat Teri!* Teri mohabbat mein dil deewana ho gaya! Ye dil ab tere naam! 🥰",
    dilkhol: "💗 *Dil Khol!* Dil khol kar baat karo, dil mein mat rakho! Khul ke jeeyo! 😊",
    gussapyaar: "😡❤️ *Gussa Pyaar!* Gussa bhi pyaar ka hi roop hai! Jo gussa kare, wo pyaar bhi karta hai! 😄",
    jasoos: "🕵️ *Jasoos!* Aap to jasus ban gaye! Kisi ki khabar nikaal rahe ho? Sambhal ke! 😏",
    tangaphanda: "🌀 *Tanga Phanda!* Ye to bara tanga phanda hai! Suljhao jaldi, warna ulajh jayega! 😅",
    muftadvice: "🆓 *Muft Advice!* Subah jaldi utho, sehat banao! Muft ki advice, faida hazar! 😄",
    nakhrebaaz: "💅 *Nakhrebaaz!* Itne nakhre? Nawabi khandan se ho kya? Thore kam karo! 😂",
    anokhapyaar: "🦄 *Anokha Pyaar!* Ye pyaar to bilkul anokha hai — aisa kahin nahi dekha! ✨",
    bhaaggaya: "🏃 *Bhaag Gaya!* Kaam dekh kar bhaag gaya? Wapas aao, zimmedari se mat bhago! 😂",
    khushnaseebi: "🌟 *Khush Naseebi!* Khush naseeb ho jo itne achay dost mile! Qadar karo! 🤗",
    ronewala: "😢 *Rone Wala!* Ro lo, dil halka ho jayega! Rone mein sharam kaisi? 💧",
    waqtguzarna: "⏳ *Waqt Guzarna!* Waqt guzar jata hai, yaadein reh jati hain! Achay lamhe banao! 🌅",
    chandsa: "🌙 *Chand Sa!* Aap ka chehra chand sa roshan hai! Chandni bhi sharma jaye! 😍",
    dostyadildar: "🤗 *Dost Ya Dildar!* Dost bhi dildar ho to kya baat! Dosti aur mohabbat ka combo! 💕",
    galatfehmi: "😕 *Galatfehmi!* Galatfehmi door karo, baat cheet se har masla hal hota hai! 🗣️",
    perfectmatch: "💑 *Perfect Match!* 100% match! Jodi to upar wala banata hai! Mubarak ho! 🎉",
    raazkhola: "🤫 *Raaz Khola!* Raaz khul gaya! Ab sab ko pata chal gaya! Shhh... 🤭",
    mohabbatdarjaa: "🌡️ *Mohabbat Darja!* Aap ki mohabbat ka darja: BUKHAAR! 104 degree! 😂",
    dua: "🤲 *Dua!* Meri dua hai ke aap hamesha khush raho! Allah khush rakhe! Ameen! 🌙",
    khwaabon: "💭 *Khwaabon!* Khwaabon ki duniya mein kho jao! Neend mein bhi muskurana! 😴✨",
    akela: "🚶 *Akela!* Akela mehsoos kar rahe ho? Main hun na! Ye bot kabhi akela nahi chorta! 🤗",
    bewafa: "💔 *Bewafa!* Bewafai ka gham mat karo! Jo gaya wo gaya, aage barho! 💪",
    chakkar: "😵‍💫 *Chakkar!* Sar chakkar kha raha hai? Pyaar mein aisa hi hota hai! Sambhal ke! 😂",
    ullubana: "🦉 *Ullu Bana!* Ullu banaya kisi ne? Hoshyar raho, dobara mat banna! 😄",
    taalibajao: "👏 *Taali Bajao!* Kya baat kahi! Taaliyan bajni chahiye! 👏👏",
    neendurai: "😴 *Neend Urai!* Kisi ne neend ura di? Mohabbat mein neend kahan! ☕",
    chatpata: "🌶️ *Chatpata!* Chatpata jawab! Maza aa gaya! Thora aur mirch lagao! 😜",
    waitingroom: "⏰ *Waiting Room!* Reply ka intezar? Sabar ka phal meetha hota hai! 😅",
    taj: "👑 *Taj!* Aap ke sar par taj sajta hai! Badshah wali personality! 🔥",
    lafangaa: "😎 *Lafangaa!* Lafanga giri band karo! Shareef bano! 😂",
    chocolatewala: "🍫 *Chocolate Wala!* Chocolate lao, dil jeeto! Meethi cheez se meethi baat! 😋",
    baatkaatna: "✂️ *Baat Kaatna!* Baat katna buri baat! Poori baat suno, phir jawab do! 👂",
    palat: "🔄 *Palat!* Palat kar dekha? Koi peeche to nahi aa raha? 😏",
    gaanasunao: "🎵 *Gaana Sunao!* Gaana sunao, mehfil sajao! Sur mein sur milao! 🎤",
    haaththamna: "🤝 *Haath Thamna!* Haath thamo, saath nibhao! Dosti ka wada! 💪",
    chuprahna: "🤫 *Chup Rehna!* Chup rehne mein hi bhalai hai! Kabhi kabhi khamoshi behtar! 😶",
    phoolonkahaar: "🌸 *Phoolon Ka Haar!* Phoolon ka haar pehnao, izzat barhao! Khushboo phailao! 🌺",
    ghoordekhna: "👀 *Ghoor Dekhna!* Itna ghoor mat dekho, nazar lag jayegi! 😂",
    bahaana: "🙄 *Bahaana!* Bahaane banana band karo! Seedhi baat karo! 😅",
    tarkeeb: "💡 *Tarkeeb!* Kya tarkeeb nikaali! Dimagh to tez hai aap ka! 🧠",
    hassichhupa: "🤭 *Hassi Chhupa!* Hassi chhupana mushkil hai! Khul kar hanso, dil khush karo! 😂",
    mobileband: "📵 *Mobile Band!* Mobile band karo, neend poori karo! Subah fresh utho! 😴",
    pagalpancert: "📜 *Pagalpan Certificate!* Ye lo aap ka official Pagalpan Certificate! Certified! 🤪",
    donobaat: "🗣️ *Dono Baat!* Dono ki baat suno, phir faisla karo! Insaaf zaroori! ⚖️",
    kaanpakadna: "👂 *Kaan Pakadna!* Kaan pakdo, maafi mango! Ghalti maan lena bari baat! 😅",
    taqdir: "🎲 *Taqdir!* Taqdir ke likhe ko koi nahi badal sakta! Mehnat karo, dua karo! 🤲",
    kapkapi: "🥶 *Kapkapi!* Kapkapi chhoot rahi hai? Thand lag rahi hai ya dar? 😂",
    taarifcommit: "👏 *Taarif Committee!* Taarif committee ka ijlaas shuru! Aap ki tareef mein do lafz! 🌹",
    captioncontest: "📸 *Caption Contest!* Tasveer par mazedaar caption likho! Best caption jeetega! 🏆",
    zyadasocha: "🤔 *Zyada Socha!* Zyada mat socho! Soch soch ke dimagh kharab ho jayega! 😅",
    ghazab: "🔥 *Ghazab!* Ghazab kar diya! Kya baat hai, kamal! 💥",
    onlinedekhna: "🟢 *Online Dekhna!* Online dekh kar khush ho gaye? Message bhi kar lo! 😏",
    dushmankadushman: "⚔️ *Dushman Ka Dushman!* Dushman ka dushman dost hota hai! Purani kahawat! 😄",
    buraanamano: "😊 *Bura Na Mano!* Bura na mano, mazaak hai! Dil par mat lo! 🤗",
    mirrormirror: "🪞 *Mirror Mirror!* Aaine mein dekho — sab se khoobsurat chehra! MashaAllah! ✨",
    mahero: "🦸 *Mera Hero!* Aap mere hero ho! Hero wali entry! 🔥",
    natkhat: "😜 *Natkhat!* Kitne natkhat ho! Shararatein band karo! 😂",
    pareshan: "😟 *Pareshan!* Pareshan mat ho! Har mushkil ke baad asaani hai! 💪",
    interview: "🎤 *Interview!* Sawal: sab se bari kamzori? Jawab: chocolate! Interview pass! 😄",
    kheltamam: "🏁 *Khel Tamam!* Khel khatam! Jeet aap ki! Champion! 🏆",
    rishtapakka: "💍 *Rishta Pakka!* Rishta pakka samjho! Mubarak ho! Mithai khilao! 🍬",
    pyaardukaan: "🏪 *Pyaar Dukaan!* Pyaar ki dukaan khol li? Muft mein banto, paisa mat lo! 😂",
    zabaansambhlo: "👅 *Zabaan Sambhlo!* Zabaan sambhal kar! Meethi zubaan se dil jeeto! 🍯",
    jhootawada: "🤥 *Jhoota Wada!* Wada khilafi buri baat! Jo kaho, wo karo! 💪",
    sonawala: "😴 *Sona Wala!* Sone ka time! Khwaabon mein milte hain! Good night! 🌙",
    gossip: "🗣️ *Gossip!* Gossip time! Lekin kisi ki burai mat karo! Halki phulki baat! ☕",
    funnyrishtedar: "😂 *Funny Rishtedar!* Har khandan mein ek funny rishtedar hota hai! Wo aap ho! 🤪",
    aankheband: "🙈 *Aankhein Band!* Aankhein band karo, khwaab dekho! Neend ka maza! 😴",
    alvidanahi: "👋 *Alvida Nahi!* Alvida nahi, phir milenge! Dooriyan dil se nahi hoti! 🤗",
    personalitytest: "🧪 *Personality Test!* Result: 100% mazedaar, 200% pyaare! Test pass! ✅",
    superpower: "⚡ *Superpower!* Aap ki superpower: doston ko hansana! Is se bari taqat kya! 😄",
    pastlife: "🔮 *Past Life!* Pichle janam mein aap zaroor shayar thay! Alfaaz mein jadoo hai! ✨",
    darksecret: "🌑 *Dark Secret!* Aap ka dark secret: raat ko chupke chocolate khate ho! Pakre gaye! 🍫😂",
    celebmatch: "🌟 *Celeb Match!* Aap bilkul apne jaise lagte ho! Unique ho, kisi se match nahi! 😄",
    lifebattery: "🔋 *Life Battery!* Battery low? Chai piyo, doston se milo, recharge ho jao! ☕",
    desimom: "👩‍🍳 *Desi Mom!* Beta, sweater pehno, thand hai! Desi mom ki fikar sab se pyaari! ❤️",
    desidad: "👨 *Desi Dad!* Parhai kaisi chal rahi hai? Desi dad ka pyaar sakht lehjay mein chhupa! 😄",
    khanajudge: "🍛 *Khana Judge!* Biryani mein aloo? Qubool! Bas maza aana chahiye! 😋",
    rishtaaunt: "👵 *Rishta Aunty!* Beta, shaadi kab kar rahe ho? Rishta aunty har jaga! 😂",
    challenge: "🎯 *Challenge!* Challenge qubool! 24 ghante bina mobile! Kar sakte ho? 😏",
    friendtype: "👥 *Friend Type!* Aap hamesha saath dene wale dost ho! Best type! 🤗",
    pakoraweather: "🌧️ *Pakora Weather!* Barish + pakoray + chai = perfect combo! Mausam ka maza! ☕",
    result: "📊 *Result!* Result aa gaya: AAP PASS! Mubarak ho! Mithai banto! 🎉",
    cricketcomm: "🏏 *Cricket Commentary!* Aur ye CHHAKKA! Crowd pagal! Kya commentary! 🎤",
    shadiprediction: "🔮 *Shaadi Prediction!* Prediction: agle saal khush khabri! Tayyari rakho! 😏💍",
    stresslevel: "😰 *Stress Level!* Stress high? Gehri saans lo, chai piyo, relax! 🧘",
    motivationalslap: "👋 *Motivational Slap!* Utho! Kaam karo! Tum kar sakte ho! Ab rona band! 💪😂",
    wikifact: "📚 *Wiki Fact!* Fact: Hansne se umar barhti hai! To hanste raho! 😄",
    animepersonality: "🎌 *Anime Personality!* Aap mein main character energy hai! Protagonist vibes! ⚡",
    weathermood: "🌤️ *Weather Mood!* Mausam suhana, mood bhi suhana! Enjoy karo! 😊",
    taunt: "😏 *Taunt!* Halka sa taunt to banta hai! Lekin pyaar se! 😄",
    gharkawifi: "📶 *Ghar Ka WiFi!* WiFi slow? Router restart karo! Desi nuskha, 100% kaam! 😂",
    lovecalc2: "💘 *Love Calc 2.0!* Calculate ho raha hai... Result: 99.9% PERFECT! 💑",
    problems: "🧩 *Problems!* Maslay to aate rehte hain! Hal bhi nikal aata hai! Hosla rakho! 💪",
    mildroast: "🔥 *Mild Roast!* Aap itne shareef ho ke roast bhi pyaar lagta hai! 😄",
    wisdomcookie: "🥠 *Wisdom Cookie!* Jo dusron ko khush rakhe, wo khud khush rehta hai! 🍪",
    monsterenergy: "⚡ *Monster Energy!* Full energy mode ON! Ab ruko mat, aage barho! 🚀",
    socialmedia: "📱 *Social Media!* Thora break lo! Asli zindagi screen ke bahar hai! 🌳",
    whatanimal: "🦁 *What Animal!* Aap sher ho! Bahadur aur dilair! 🦁",
    typingspeed: "⌨️ *Typing Speed!* Itni tez typing? Pata chalta hai bohat chat karte ho! 😂",
    nightowl: "🦉 *Night Owl!* Raat ko jagna, din ko sona! Ullu wali routine! 😴",
    pizzaorbiryani: "🍕🍛 *Pizza or Biryani?* Sahi jawab: BIRYANI! Is mein behes ki gunjaish nahi! 😋",
    emotionaldamage: "💔 *Emotional Damage!* Dil toot gaya? Arre, mazak tha! Sambhalo! 😂",
    complainbox: "📦 *Complain Box!* Shikayat darj karo! Hal jald milega... shayad! 😅",
    numbergame: "🔢 *Number Game!* 1 se 10 tak number socho... 7 socha na? Pakre gaye! 😏",
    coinflip: "🪙 *Coin Flip!* Sikka uchala... Aaya: HEAD! Qismat aap ke saath! 🍀",
    naammatlab: "📛 *Naam Matlab!* Aap ke naam ka matlab: khushiyan bantne wala! Kya khoob! ✨",
    compliment2: "💐 *Compliment!* Aap ki smile dekh kar phool bhi sharma jayein! Bohat pyaare ho! 😊",
    examseason: "📝 *Exam Season!* Parhai karo! Mobile side par rakho! Best of luck! 🍀",
    pakfact: "🇵🇰 *Pak Fact!* Pakistan mein mehmaan ko bas thora sa khana khilaya jata hai — phir dobara! 😂",
    storygenerate: "📖 *Story Generate!* Ek tha chanda, ek thi chandni... Kahani jari rahegi! Agla part? 😄",
    botroast: "🤖 *Bot Roast!* Main bot hun, roast nahi hota! Lekin aap ki koshish achi thi! 😎",
    weeklyreport: "📈 *Weekly Report!* Is haftay: 100% masti, 0% kaam! Agle haftay sudhar karna! 😂",
    soulcolor: "🎨 *Soul Color!* Aap ki rooh ka rang: SUNHERA! Chamakdar aur garam! ✨",
    desiwisdom: "🧓 *Desi Wisdom!* Jitni chadar, utne paon phelao! Dadi amma ki hikmat! 💡",
    kindness: "💝 *Kindness!* Narmi se bara koi hathiyar nahi! Meherban raho! 🤗",
    newcmds: "🆕 *New Commands!* Naye commands aa gaye! .menu likh kar dekho! Maza aayega! 🎉",
};

async function funTextCommand(sock, chatId, msg, trigger) {
    const key = String(trigger || '').toLowerCase();
    const text = RESPONSES[key];
    if (!text) return;
    try {
        await sock.sendMessage(chatId, { text }, { quoted: msg });
    } catch (e) {
        console.error('FunText command error:', e.message);
    }
}

funTextCommand.TRIGGERS = Object.keys(RESPONSES);

module.exports = funTextCommand;
